"""Supply-chain pins: hashed lockfiles, SHA-pinned Actions, hard CI SBOM gate.

O.8 / O15. These tests pin local, reviewable artefacts only — not that an
install is uncompromised in the wild, and not that the Docker image path is
hash-locked (it still installs from pyproject floors).

Three things decay silently without a test:

1. **Every GitHub Action is pinned to a commit SHA.** A tag is a mutable
   pointer. ``release.yml`` runs with ``id-token: write`` — the PyPI Trusted
   Publishing identity — so whoever controls a tag at the moment a release
   runs can mint a token and publish as this project.

2. **Every package CI installs is pinned to a version and a SHA-256.** Floors
   (``>=``) make a green run a statement about one moment on PyPI rather than
   about the commit.

3. **The SBOM describes the published artifact, not the toolchain.** It is
   generated by ``cyclonedx-py`` against the clean venv the wheel is installed
   into, so it reports what ``pip install veritas-research`` actually produces.
   Generating it from the CI environment instead would over-report by ~100
   dev-only packages that never ship, and an SBOM with the wrong subject is
   worse than none — it invites a check that passes against the wrong list.

There is deliberately **one** SBOM generator. A second, lock-derived one was
written and removed during this change: a lock states what pip was *told* to
install, while ``cyclonedx-py`` reports what an environment *contains*, and two
artifacts both called "the SBOM" is the two-sources-of-truth failure this
repository forbids elsewhere.
"""

from __future__ import annotations

import importlib.util
import re
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
WORKFLOWS = REPO / ".github" / "workflows"
RUNTIME_LOCK = REPO / "requirements.lock"
DEV_LOCK = REPO / "requirements-dev.lock"

_USES_RE = re.compile(
    r"^\s*-?\s*uses:\s+(?P<action>[\w.-]+/[\w./-]+)@(?P<ref>\S+)(?P<rest>.*)$",
    re.MULTILINE,
)
_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
_LOCK_ENTRY_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9._-]+)==(?P<version>[^\s\\]+)\s*\\\s*\n"
    r"\s*--hash=sha256:(?P<digest>[0-9a-f]{64})\s*$",
    re.MULTILINE,
)


def _load_script(name: str):
    """Import a file from scripts/, which is not an importable package."""
    path = REPO / "scripts" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"_veritas_script_{name}", path)
    assert spec and spec.loader, f"cannot load scripts/{name}.py"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _workflow_files() -> list[Path]:
    files = sorted(WORKFLOWS.glob("*.yml")) + sorted(WORKFLOWS.glob("*.yaml"))
    assert files, "no workflow files found"
    return files


def _uses_entries() -> list[tuple[Path, str, str, str]]:
    entries = []
    for path in _workflow_files():
        for match in _USES_RE.finditer(path.read_text(encoding="utf-8")):
            entries.append(
                (path, match.group("action"), match.group("ref"), match.group("rest"))
            )
    assert entries, "no `uses:` references found — the parser is probably wrong"
    return entries


def _lock_entries(path: Path) -> dict[str, tuple[str, str]]:
    assert path.is_file(), f"missing lockfile: {path.name}"
    text = path.read_text(encoding="utf-8")
    entries = {
        m.group("name").lower().replace("_", "-"): (m.group("version"), m.group("digest"))
        for m in _LOCK_ENTRY_RE.finditer(text)
    }
    assert entries, f"{path.name} parsed to zero hash-pinned entries"
    return entries


def _version_tuple(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in re.findall(r"\d+", version)[:3])


# --------------------------------------------------------------------------
# 1. Actions are pinned to immutable commits
# --------------------------------------------------------------------------


def test_every_workflow_uses_is_full_commit_sha():
    """Every `uses:` must pin a full 40-char commit SHA (optional # version comment)."""
    unpinned = [
        f"{path.name}: {action}@{ref}"
        for path, action, ref, _ in _uses_entries()
        if not _SHA_RE.match(ref)
    ]
    assert not unpinned, (
        "GitHub Actions must be pinned to a full 40-character commit SHA, not a "
        "mutable tag or branch:\n  " + "\n  ".join(unpinned)
    )


def test_every_pinned_action_records_the_version_it_pins():
    """A bare SHA is unreviewable; the trailing comment says what it is."""
    missing = [
        f"{path.name}: {action}@{ref[:12]}"
        for path, action, ref, rest in _uses_entries()
        if not re.search(r"#\s*v?\d", rest)
    ]
    assert not missing, (
        "every pinned action needs a trailing `# vX.Y.Z` comment so the pin can "
        "be read and updated:\n  " + "\n  ".join(missing)
    )


def test_release_workflow_publish_step_is_pinned():
    """The one step that holds publishing authority, called out explicitly."""
    text = (WORKFLOWS / "release.yml").read_text(encoding="utf-8")
    match = re.search(r"uses:\s+pypa/gh-action-pypi-publish@(\S+)", text)
    assert match, "release.yml no longer uses pypa/gh-action-pypi-publish"
    assert _SHA_RE.match(match.group(1)), (
        "the PyPI publish step runs with id-token: write and must be pinned to a "
        f"commit SHA, found {match.group(1)!r}"
    )


# --------------------------------------------------------------------------
# 2. Lockfiles pin versions and artifact hashes
# --------------------------------------------------------------------------


def test_lockfiles_pin_transitive_deps_with_hashes():
    """Committed requirements.lock + requirements-dev.lock pin == with sha256 hashes."""
    runtime = _lock_entries(RUNTIME_LOCK)
    dev = _lock_entries(DEV_LOCK)
    for name, (version, _digest) in runtime.items():
        assert name in dev, f"{name} in requirements.lock but missing from requirements-dev.lock"
        assert dev[name][0] == version, (
            f"{name} version mismatch: runtime {version} vs dev {dev[name][0]}"
        )


def test_every_lock_entry_carries_an_exact_version_and_hash():
    for path in (RUNTIME_LOCK, DEV_LOCK):
        text = path.read_text(encoding="utf-8")
        requirement_lines = [
            line
            for line in text.splitlines()
            if line.strip() and not line.lstrip().startswith(("#", "--hash="))
        ]
        assert len(requirement_lines) == len(_lock_entries(path)), (
            f"{path.name}: every non-comment line must parse as a hash-pinned "
            "requirement; a line that does not is an unpinned install"
        )


def test_lock_pins_every_direct_requirement():
    """Nothing the floors declare may be absent from the matching lock."""
    runtime = _lock_entries(RUNTIME_LOCK)
    dev = _lock_entries(DEV_LOCK)
    for name, lock in (("requirements.txt", runtime), ("requirements-dev.txt", dev)):
        direct = set()
        for line in (REPO / name).read_text(encoding="utf-8").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("-r"):
                continue
            match = re.match(r"^([A-Za-z0-9_.-]+)", line)
            assert match, f"unparseable requirement in {name}: {line!r}"
            direct.add(match.group(1).lower().replace("_", "-"))
        missing = sorted(direct - set(lock))
        assert not missing, f"direct requirements absent from {name}'s lock: {missing}"


def test_lock_pins_are_not_below_requirements_floors():
    """Exact lock versions must never be looser than requirements.txt floors."""
    locked = _lock_entries(RUNTIME_LOCK)
    for line in (REPO / "requirements.txt").read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith("-r") or ">=" not in line:
            continue
        package, floor = line.split(">=", 1)
        key = package.strip().lower().replace("_", "-")
        pinned = locked[key][0]
        assert _version_tuple(pinned) >= _version_tuple(floor.strip()), (
            f"{key} is locked at {pinned}, below its declared floor {floor.strip()}"
        )


def test_lock_satisfies_the_declared_floors():
    """Dev lock may be stricter than floors, never looser."""
    locked = _lock_entries(DEV_LOCK)
    for name in ("requirements.txt", "requirements-dev.txt"):
        for line in (REPO / name).read_text(encoding="utf-8").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("-r") or ">=" not in line:
                continue
            package, floor = line.split(">=", 1)
            # Strip trailing upper bounds like ",<2" if ever present.
            floor_ver = floor.strip().split(",")[0].strip()
            key = package.strip().lower().replace("_", "-")
            pinned = locked[key][0]
            assert _version_tuple(pinned) >= _version_tuple(floor_ver), (
                f"{key} is locked at {pinned}, below its declared floor {floor_ver}"
            )


def test_lock_versions_satisfy_every_declared_bound():
    """A floor is half a requirement; the ceiling is the other half.

    `test_lock_satisfies_the_declared_floors` above strips upper bounds by
    design, so nothing ever compared a locked version against a ceiling.
    Narrowing one without regenerating leaves a lock that installs precisely
    the version the ceiling was written to exclude, and the disagreement stays
    invisible until someone regenerates — at which point versions move for
    reasons unrelated to whatever they were changing.

    Ceilings here are behavioural, not caution: `mcp<2` records that mcp 2.0.0
    removed `mcp.server.fastmcp`, the surface `veritas-mcp` is built on. A lock
    that ignores that bound ships an extra which cannot serve.
    """
    from packaging.requirements import Requirement
    from packaging.version import Version

    checked = 0
    for source, lock_path in (
        ("requirements.txt", RUNTIME_LOCK),
        ("requirements-dev.txt", DEV_LOCK),
    ):
        locked = _lock_entries(lock_path)
        for line in (REPO / source).read_text(encoding="utf-8").splitlines():
            line = line.split("#", 1)[0].strip()
            if not line or line.startswith("-r"):
                continue
            requirement = Requirement(line)
            key = requirement.name.lower().replace("_", "-")
            assert key in locked, (
                f"{key} is declared in {source} but absent from {lock_path.name}"
            )
            pinned = locked[key][0]
            # prereleases=True: the resolver legitimately pins a prerelease when
            # that is what satisfies the range, and rejecting them here would
            # fail on a lock that is correct.
            assert requirement.specifier.contains(Version(pinned), prereleases=True), (
                f"{lock_path.name} pins {key}=={pinned}, which {source} excludes "
                f"({requirement.specifier}). A bound changed without the lock being "
                "regenerated — run: python scripts/lock_requirements.py"
            )
            checked += 1

    assert checked, "no declared requirements were checked — the parser is wrong"


def test_lock_declares_the_platform_its_markers_came_from():
    """The lock is only correct for the environment that resolved it."""
    for path in (RUNTIME_LOCK, DEV_LOCK):
        header = path.read_text(encoding="utf-8")[:2000]
        assert "linux" in header, f"{path.name} must state the platform it targets"
        assert "3.12" in header, f"{path.name} must state the Python version it targets"


def test_lock_generator_refuses_to_run_off_target():
    """Fail-closed: a wrong lock cannot be generated, only refused."""
    lock_script = _load_script("lock_requirements")
    original = lock_script.TARGET_PLATFORM
    try:
        lock_script.TARGET_PLATFORM = "definitely-not-this-platform"
        with pytest.raises(SystemExit) as excinfo:
            lock_script._assert_on_target()
        assert excinfo.value.code == 1
    finally:
        lock_script.TARGET_PLATFORM = original


# --------------------------------------------------------------------------
# 3. CI actually uses the lock; SBOM is a hard gate
# --------------------------------------------------------------------------


def test_ci_install_uses_require_hashes():
    """test + security-scan jobs must install via --require-hashes from the dev lock."""
    text = (WORKFLOWS / "ci.yml").read_text(encoding="utf-8")
    required = "pip install --require-hashes -r requirements-dev.lock"
    assert required in text, (
        "ci.yml must install with "
        f"{required!r} on the test and security-scan paths"
    )
    assert text.count(required) >= 2, (
        f"{required!r} must appear in both the test and security-scan install steps"
    )


def test_ci_sbom_step_is_hard_gate():
    """ci.yml must generate an SBOM and upload it; generation must not soft-fail."""
    text = (WORKFLOWS / "ci.yml").read_text(encoding="utf-8")
    lower = text.lower()
    assert "sbom" in lower, "ci.yml has no SBOM step"
    assert re.search(
        r"generate_sbom|cyclonedx|syft|cdxgen",
        text,
        re.IGNORECASE,
    ), "ci.yml SBOM step must invoke a known generator"
    assert re.search(
        r"upload-artifact|actions/upload-artifact@",
        text,
        re.IGNORECASE,
    ), "ci.yml must upload the SBOM as a workflow artifact"

    for match in re.finditer(r"(?is)([^\n]*sbom[^\n]*(?:\n[^\n]*){0,12})", text):
        block = match.group(0)
        assert "continue-on-error" not in block, (
            "SBOM path must not set continue-on-error:\n" + block
        )
        assert "|| true" not in block, "SBOM path must not soft-fail with || true:\n" + block
        assert "||true" not in block.replace(" ", ""), (
            "SBOM path must not soft-fail with ||true:\n" + block
        )


def test_bandit_remains_hard_gate_in_ci():
    """bandit -ll must stay a non-soft-fail CI step."""
    text = (WORKFLOWS / "ci.yml").read_text(encoding="utf-8")
    assert "bandit -r veritas scripts -ll -q" in text
    bandit_idx = text.index("bandit -r veritas scripts -ll -q")
    window = text[max(0, bandit_idx - 400) : bandit_idx + 120]
    assert "continue-on-error" not in window
    assert "|| true" not in window


def test_sbom_subject_is_the_artifact_venv_not_the_ci_toolchain():
    """The SBOM must describe what a buyer installs.

    `cyclonedx-py environment` reports whatever environment it is pointed at.
    Pointed at the CI job it would list pytest, ruff, bandit and twine — none
    of which ship — and the resulting document would answer the wrong question
    while looking entirely plausible.
    """
    text = (WORKFLOWS / "ci.yml").read_text(encoding="utf-8")
    match = re.search(r"cyclonedx-py environment (\S+)", text)
    assert match, "ci.yml does not generate the SBOM from an explicit environment"
    assert match.group(1) == "/tmp/venv", (
        "the SBOM must be generated from the clean venv the wheel is installed "
        f"into, not {match.group(1)!r}"
    )


def test_sbom_generation_asserts_dev_tooling_is_absent():
    """The subject check is enforced in CI, not just intended here."""
    text = (WORKFLOWS / "ci.yml").read_text(encoding="utf-8")
    assert "SBOM subject is wrong" in text, (
        "ci.yml must fail the job if the generated SBOM names dev-only tooling"
    )


def test_workflow_sbom_flags_exist_in_the_installed_generator():
    """Catch CLI drift locally instead of in CI.

    The workflow invokes cyclonedx-py through a shell, so a flag that does not
    exist is not a syntax error anywhere — it fails only when the job runs.
    (`--outfile` is not a cyclonedx-py option; `--output-file` is. That cost a
    CI round trip.) Upgrading the generator can rename a flag the same way, so
    this checks the options the workflows actually pass against the help text
    of the installed version.
    """
    generator = shutil.which("cyclonedx-py")
    if generator is None:
        pytest.skip("cyclonedx-py is not installed in this environment")

    help_text = subprocess.run(
        [generator, "environment", "--help"],
        capture_output=True,
        text=True,
        timeout=60,
    ).stdout

    used: set[str] = set()
    for path in _workflow_files():
        text = path.read_text(encoding="utf-8")
        for block in re.finditer(r"cyclonedx-py environment(.*?)(?:\n\s*\n|\n\s*-\s+name:)", text, re.S):
            used.update(re.findall(r"(--[a-z][a-z-]+)", block.group(1)))

    assert used, "no cyclonedx-py invocation found in the workflows"
    missing = sorted(flag for flag in used if flag not in help_text)
    assert not missing, (
        f"the workflows pass options the installed cyclonedx-py does not accept: {missing}"
    )


def test_sbom_generator_comes_from_the_hashed_lock():
    """A generator fetched at run time would be an unpinned supply-chain path."""
    assert "cyclonedx-bom" in (REPO / "requirements-dev.txt").read_text(encoding="utf-8")
    assert "cyclonedx-bom" in _lock_entries(DEV_LOCK), (
        "cyclonedx-bom must be hash-pinned in the dev lock, or the SBOM "
        "generator is itself an unverified download"
    )


def test_release_workflow_builds_from_the_hashed_lock():
    """The tooling that builds a published artifact is part of its supply chain."""
    text = (WORKFLOWS / "release.yml").read_text(encoding="utf-8")
    assert "pip install --require-hashes -r requirements-dev.lock" in text, (
        "release.yml must install build tooling from the hashed lock"
    )


def test_release_job_does_not_combine_publish_identity_with_write_access():
    """Least privilege on the one job that can publish as this project.

    `id-token: write` mints the PyPI Trusted Publishing token. Adding
    `contents: write` to the same job — e.g. to attach an SBOM with
    `gh release upload` — would widen the blast radius of the most sensitive
    job in the repository.
    """
    text = (WORKFLOWS / "release.yml").read_text(encoding="utf-8")
    # This workflow's comments discuss `contents: write` in order to record why
    # it is absent, so the check must read directives, not prose.
    directives = "\n".join(
        line for line in text.splitlines() if not line.lstrip().startswith("#")
    )
    assert "id-token: write" in directives, "release.yml no longer uses Trusted Publishing"
    assert "contents: write" not in directives, (
        "the release job holds id-token: write; granting it contents: write too "
        "combines publishing authority with repository write access"
    )
    assert "gh release upload" not in directives, (
        "attaching to a release needs contents: write — keep it out of this job"
    )


def test_no_unhashed_dependency_install_remains_in_ci():
    """Every pip install either upgrades pip itself or verifies hashes.

    A single unhashed `pip install -r requirements-dev.txt` anywhere would
    quietly restore the floors-resolved-at-run-time behaviour the locks exist
    to remove.
    """
    offenders = []
    for path in _workflow_files():
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if not re.search(r"\bpip install\b", stripped) or stripped.startswith("#"):
                continue
            if "--require-hashes" in stripped:
                continue
            # Bootstrapping pip itself, and installing the just-built wheel,
            # are the two intended exceptions.
            if re.search(r"pip install --upgrade pip\s*$", stripped):
                continue
            if "dist/*.whl" in stripped:
                continue
            offenders.append(f"{path.name}: {stripped}")
    assert not offenders, "unhashed dependency installs remain:\n  " + "\n  ".join(offenders)
